# Using Node 20 to ensure crypto support
FROM node:20-alpine

WORKDIR /backend  # Changed to match your root folder

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3000

CMD ["node", "dist/main"]